#include <iostream>
#include <cstdio>
#include <utility>
#include <vector>
#include <unordered_map>
#include <map>
#include <string>
#include <string.h>
#include <stdlib.h>
#include <set>
#include <algorithm>